# deploy/helm/neo4j/values.yaml

neo4j:
  name: "neo4j-cluster"
  edition: "community"
  
  core:
    # Community Edition does NOT support Clustering. 
    # Must be 1. If you need HA, upgrade to Enterprise.
    numberOfServers: 1 
    
    resources:
      requests:
        cpu: "2"
        memory: "8Gi"
    
  volumes:
    data:
      mode: "default" # Dynamic binding
      storageClassName: "gp3"
      size: "100Gi"